apiVersion: v1
kind: ConfigMap
metadata:
  name: zsp-backend-configmap
  namespace: develop
data:
  PORT: "3000"
  NODE_ENV: development
  NODE_SHARED_VOLUME_PATH: /app/assets
  LOG_LEVEL: silly
  BUCKET_NAME: user_uploaded_documents
  FRONTEND_URL: https://dashboard-develop.zoopsign.com
  JAVA_SVC_URL: https://int-api-develop.zoopsign.com/esign/add-sign
  SENDGRID_EMAIL: esign@zoopsign.com
  BUCKET: zsp-shared-bucket
  MNT_DIR: /app/assets
  WHATSAPP_CLOUD_SVC_URL: https://graph.facebook.com/v15.0
  WHATSAPP_PHONE_NUMBER_ID: "111342905114971"
  ZOOP_URL: https://live.zoop.one/contract/esign
  WHATSAPP_ESIGN_INVITATION_TEMPLATE: zoopsign_esign_invitation
  DOCS_BUCKET_NAME: test-pdf-store-esign
  ESIGN_WEBHOOK_URL: http://api-develop.zoopsign.com/api/document/webhook
  ESIGN_INIT_URL: https://esign.zoop.one/v4/viewer
  LOGGER_TYPE: console
