apiVersion: v1
kind: ConfigMap
metadata:
  name: zsp-backend-configmap
  namespace: staging
data:
  PORT: "3000"
  NODE_ENV: staging
  NODE_SHARED_VOLUME_PATH: /app/assets/pdf
  LOG_LEVEL: debug
  BUCKET_NAME: zoopsign_staging_documents
  FRONTEND_URL: https://dashboard-staging.zoopsign.com
  JAVA_SVC_URL: https://int-api-staging.zoopsign.com/esign/add-sign
  SENDGRID_EMAIL: esign@zoopsign.com
  BUCKET: zsp-shared-bucket-staging
  MNT_DIR: /app/assets
  WHATSAPP_CLOUD_SVC_URL: https://graph.facebook.com/v15.0
  WHATSAPP_PHONE_NUMBER_ID: "111342905114971"
  ZOOP_URL: https://live.zoop.one/contract/esign
  WHATSAPP_ESIGN_INVITATION_TEMPLATE: zoopsign_esign_invitation
  DOCS_BUCKET_NAME: test-pdf-store-esign
  ESIGN_WEBHOOK_URL: https://api-staging.zoopsign.com/api/document/webhook
  ESIGN_INIT_URL: https://esign.zoop.one/v4/viewer
  LOGGER_TYPE: console
