# To containerize you app this step helps you to build on GCP
# This is a yaml file, like all others, to build and store you
# containerize application to Google Container Registry
# Change the PROJECT_NAME to the name of your project
steps:
  # - id: "Pull the Previous Image"
  #   name: "gcr.io/cloud-builders/docker"
  #   entrypoint: "bash"
  #   args:
  #     [
  #       "-c",
  #       "docker pull asia.gcr.io/$PROJECT_ID/zsp-backend:$BRANCH_NAME || exit 0",
  #     ]

  - id: "Build Zoopsign NodeJS Backend"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
         "--build-arg",
        "SSH_KEY=$_SSH_KEY",
        "--build-arg",
        "GCP_SA_JSON=$_GCP_SA_JSON",
        "-t",
        "asia.gcr.io/$PROJECT_ID/zsp-backend:$SHORT_SHA",
        "-t",
        "asia.gcr.io/$PROJECT_ID/zsp-backend:$BRANCH_NAME",
        "--cache-from",
        "asia.gcr.io/$PROJECT_ID/zsp-backend:$BRANCH_NAME",
        ".",
      ]
  - id: "Push Zoopsign NodeJS Backend"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/zsp-backend:$SHORT_SHA"]

  # The short sha is already there but we are tagging this image with branch name
  # so that we can use it to cache from
  - id: "Tag Image Based on Branch"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "container",
        "images",
        "add-tag",
        "asia.gcr.io/$PROJECT_ID/zsp-backend:$SHORT_SHA",
        "asia.gcr.io/$PROJECT_ID/zsp-backend:$BRANCH_NAME",
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - beta
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=asia.gcr.io/$PROJECT_ID/zsp-backend:$SHORT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$SHORT_SHA,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--port=3000'
      - '--min-instances=1'
      - '--max-instances=3'
      - '--execution-environment=gen2'
      - '--vpc-connector=serverless-connector'
      - '--vpc-egress=all-traffic'
      - '--allow-unauthenticated'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

timeout: 1800s
